### ISSUE TITLE
Affixed bar on detail page jumps (Safari only)

### ISSUE THREAD

**Issue by CloudNiner** [azavea/imls-museum-data#101]
Reproduced on Safari 8

**Comment by CloudNiner** [comment]
@designmatty have you seen this behavior at all? I was unable to reproduce just now. Wanted to check before I close this.

**Comment by designmatty** [comment]
Yeah I only was able to reproduce on the search results page though. The fix is easy though and I push it up in a second.

**Comment by CloudNiner** [comment]
Awesome thanks!
