### ISSUE TITLE
Minor Text Edits to MuseumStat Site from IMLS General Counsel

### ISSUE THREAD

**Issue by nevillevak** [azavea/imls-museum-data#129]
IMLS' general counsel has reviewed all the text of the MuseumStat site, and has only two minor edits, one on the "About" page and one on the "Contact Us" page. We are hoping to be able to officially "launch" the site soon, but it is taking a bit longer due to some leadership changes at IMLS. I will let you know as soon as we're ready to go.

Here are the two edits.
1. "About the Data" section of the "About" page. Replace current text with:
MuseumStat uses two key types of data, the Museum Universe Data File (MUDF) and the American Community Survey (ACS) of the U.S. Census Bureau. The MUDF is most comprehensive data file of museums in the United States, compiled through an ongoing process and updated twice each year. The information contained in the MUDF is derived from a variety of public sources, primarily information from tax-exempt nonprofit organizations from the Internal Revenue Service. There are inherent limitations in the use of such administrative information. Although steps were taken to improve data quality, we cannot attest to overall accuracy and quality of the information contained within. We advise users to develop strategies for addressing these limitations.
The ACS is an ongoing statistical survey of the U.S. Census Bureau that gathers in-depth information on individuals and households throughout the country. MuseumStat uses the ACS 5-year estimates from 2009-2013, which allows for analysis down to the block group level.

2. On the contact us page, correct the IMLS name written out to state "Institute of Museum and Library Services" not "Institute for..."

**Comment by CloudNiner** [comment]
Closed by #130
