### ISSUE TITLE
Feedback on UI/UX/Functionality Updates

### ISSUE THREAD

**Issue by nevillevak** [azavea/imls-museum-data#145]
- In search results, change the word "NEAR" to "IN"

- Because the map displayed when searching for a city or zip is usually showing a region larger than the number of results, one of two options should be done. (1) Include small text under the "### RESULTS FOUND IN ######" stating "Map may show larger area. Results below are for your search area." or similar. (2) If feasible, show a map boundary around the city or zip code selected.

- Change the analysis area text to: "Analysis Area: ## sq. miles" (this is more understandable to our user base).

**Comment by jbranigan** [comment]
@nevillevak - Thanks for the feedback. Showing the boundary of the city/zip would be a fair amount of extra effort and would have additional data requirements, but including the text is simple. We'll make these text changes shortly and will keep you posted.

**Comment by CloudNiner** [comment]
These text changes were just pushed to MuseumStat and are now live as well, so you can take a look.
