### ISSUE TITLE
print stylesheet

### ISSUE THREAD

**Issue by designmatty** [azavea/imls-museum-data#54]

**Comment by sharph** [comment]
Will open separate issues for d3 and map key.

**Comment by jbranigan** [comment]
This doesn't seem to have been applied.

**Comment by CloudNiner** [comment]
Print stylesheet seems to be ok, with the exception of #88 and #89 which will be closed separately. I think is likely due to an out of date deployment on the museumstat bucket. Will wait to close until we redeploy.

**Comment by CloudNiner** [comment]
Closing, print stylesheet is correct after yesterday's deploy.
